/*
 * Sync for the collection tracker.
 *
 * The app works entirely offline and always has. This adds a shared copy so a
 * collection survives a lost tablet and shows up on a parent's phone, without
 * asking a six-year-old to hold an account.
 *
 * How it works
 * ------------
 * One "family code" — four words — identifies a collection. Holding the code
 * is what grants access; there is no password because there is no user. The
 * code is generated by the server, never chosen, so it cannot be a birthday.
 *
 * The client pushes everything it has, the server merges it into what it holds
 * and returns the result, and the client adopts that. The merge lives only
 * here (see merge.js), so two devices can never disagree about what merging
 * means. A device that has just been reinstalled pushes {} and receives the
 * whole collection back, rather than erasing it.
 *
 * Staying inside the free tier
 * ----------------------------
 * Workers KV allows 1,000 writes a day but 100,000 reads. An enthusiastic
 * afternoon could genuinely produce hundreds of pushes, so:
 *
 *   - a push whose merged result equals what is already stored costs a READ
 *     and nothing else, which is the common case when several devices are
 *     open at once;
 *   - a photo is only written when its hash changes;
 *   - the client debounces and batches (see app.js).
 *
 * Rate limiting uses the Workers rate limiting binding rather than a KV
 * counter, precisely because a KV counter would spend the write budget it was
 * meant to protect.
 */

import { mergeAll } from './merge.js';
import { makeCode, normaliseCode } from './code.js';

/** Photos are shrunk to 480px before they ever leave the device. */
const MAX_PHOTO_BYTES = 512 * 1024;
const MAX_BODY_BYTES = 1024 * 1024;
const MAX_PHOTOS = 1000;

const json = (body, status = 200, extra = {}) => new Response(JSON.stringify(body), {
  status,
  headers: { 'Content-Type': 'application/json; charset=utf-8', ...extra },
});

/*
 * Only the app's own origin may call this from a browser. It is not a security
 * boundary on its own — anything can send a request with curl — but it stops a
 * random page a child opens from quietly reading the family's collection using
 * a code cached in their browser.
 */
function corsHeaders(request, env) {
  const origin = request.headers.get('Origin') || '';
  const allowed = (env.ALLOWED_ORIGINS || '').split(',').map((s) => s.trim()).filter(Boolean);
  const ok = allowed.length === 0 || allowed.includes(origin);
  if (!ok || !origin) return null;
  return {
    'Access-Control-Allow-Origin': origin,
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type,X-Family-Code,X-Photo-Hash',
    'Access-Control-Max-Age': '86400',
    Vary: 'Origin',
  };
}

/** Progress for a whole family, all sets together. It is only ~12KB full. */
const progressKey = (code) => `p:${code}`;
const photoIndexKey = (code) => `idx:${code}`;
const photoKey = (code, setId, figureId) => `ph:${code}:${setId}:${figureId}`;

/*
 * Catalogue pictures live in their own namespace, deliberately.
 *
 * A catalogue picture shows what a figure looks like BEFORE it is found, so a
 * child knows what he is hunting. His own photo replaces it once he finds one.
 * The two therefore coexist for the same figure, and sharing a key would mean
 * the seed tool and a phone taking a photo silently overwriting each other.
 *
 * These are never bundled into the repo. The repo is public and a file in it is
 * fetchable whatever the app chooses to render, so manufacturer artwork there
 * would be published to the world; here it is reachable only with the family
 * code, which is the difference between publishing and keeping a copy at home.
 */
const catalogueIndexKey = (code) => `cidx:${code}`;
const catalogueKey = (code, setId, figureId) => `cat:${code}:${setId}:${figureId}`;

/*
 * Which photos exist, as an explicit document rather than a KV list().
 *
 * This is not a premature optimisation — list() is EVENTUALLY CONSISTENT, and
 * measured against the deployed worker a freshly uploaded photo took about
 * twenty seconds to show up in it. Reading a single key is strongly
 * consistent, so an index key means a photo taken on the tablet is offered to
 * the phone immediately, and a deleted one stops being offered immediately
 * rather than being resurrected for the next minute.
 *
 * The trade: two devices uploading different photos in the same instant can
 * have one index entry clobber the other, since this is a read-modify-write.
 * The photo itself is still stored and nothing is lost; it simply is not
 * advertised until that device writes another photo. For a family app where
 * photos are taken occasionally, that is a better failure than the delay.
 */
async function readIndex(env, key) {
  try {
    return JSON.parse(await env.COLLECT.get(key) || '{}') || {};
  } catch {
    return {};
  }
}

async function writeIndex(env, key, index) {
  await env.COLLECT.put(key, JSON.stringify(index));
}

const readPhotoIndex = (env, code) => readIndex(env, photoIndexKey(code));
const writePhotoIndex = (env, code, index) => writeIndex(env, photoIndexKey(code), index);
const readCatalogueIndex = (env, code) => readIndex(env, catalogueIndexKey(code));
const writeCatalogueIndex = (env, code, index) => writeIndex(env, catalogueIndexKey(code), index);

/** Ids come from our own set files, so anything exotic is a bug or an attack. */
const SAFE_ID = /^[a-z0-9][a-z0-9-]{0,127}$/;

async function limited(request, env) {
  if (!env.RATE_LIMITER) return false;
  // Keyed on IP: guessing a code is the only attack worth the effort, and it
  // needs volume from somewhere.
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  const { success } = await env.RATE_LIMITER.limit({ key: ip });
  return !success;
}

async function readCode(request, env) {
  const raw = request.headers.get('X-Family-Code');
  const code = normaliseCode(raw);
  if (!code) return null;
  return code;
}

async function handle(request, env) {
  const url = new URL(request.url);
  const path = url.pathname.replace(/\/+$/, '') || '/';

  if (path === '/' || path === '/health') {
    return json({ ok: true, service: 'collect-sync' });
  }

  // A new code needs no credentials — that is the point of it.
  if (path === '/v1/new' && request.method === 'POST') {
    for (let attempt = 0; attempt < 5; attempt += 1) {
      const code = makeCode();
      // Vanishingly unlikely at 2^32, but a collision would hand one family
      // another family's collection, so it is checked rather than assumed.
      if (await env.COLLECT.get(progressKey(code)) === null) {
        await env.COLLECT.put(progressKey(code), JSON.stringify({}));
        return json({ code });
      }
    }
    return json({ error: 'could not allocate a code' }, 503);
  }

  const code = await readCode(request, env);
  if (!code) return json({ error: 'that is not a family code' }, 401);

  if (path === '/v1/collection') {
    if (request.method === 'GET') {
      const stored = JSON.parse(await env.COLLECT.get(progressKey(code)) || '{}');
      return json({
        progress: stored,
        photos: await readPhotoIndex(env, code),
        catalogue: await readCatalogueIndex(env, code),
        serverTime: Date.now(),
      });
    }

    if (request.method === 'POST') {
      const raw = await request.text();
      if (raw.length > MAX_BODY_BYTES) return json({ error: 'too much' }, 413);
      let body;
      try { body = JSON.parse(raw); } catch { return json({ error: 'not json' }, 400); }

      const now = Date.now();
      const storedRaw = await env.COLLECT.get(progressKey(code));
      const stored = JSON.parse(storedRaw || '{}');
      const merged = mergeAll(stored, body && body.progress, now);

      /*
       * Only write when something actually changed. With several devices open
       * this is usually a no-op, and a no-op that costs a write would burn the
       * daily budget for nothing.
       */
      const next = JSON.stringify(merged);
      if (next !== JSON.stringify(stored)) await env.COLLECT.put(progressKey(code), next);

      return json({
        progress: merged,
        photos: await readPhotoIndex(env, code),
        catalogue: await readCatalogueIndex(env, code),
        serverTime: now,
      });
    }
    return json({ error: 'method' }, 405);
  }

  /*
   * Photos and catalogue pictures differ only in which namespace they land in,
   * so one handler serves both rather than two that can drift apart.
   *
   * Both are writable with the family code. The seed tool being the only thing
   * that writes catalogue pictures is a convention of ours, not something the
   * worker can enforce: it authenticates with the same code the app does, so
   * there is nothing here to tell them apart.
   */
  const image = /^\/v1\/(photo|catalogue)\/([^/]+)\/([^/]+)$/.exec(path);
  if (image) {
    const kind = image[1];
    const setId = decodeURIComponent(image[2]);
    const figureId = decodeURIComponent(image[3]);
    if (!SAFE_ID.test(setId) || !SAFE_ID.test(figureId)) {
      return json({ error: 'bad id' }, 400);
    }

    const isPhoto = kind === 'photo';
    const key = isPhoto ? photoKey(code, setId, figureId) : catalogueKey(code, setId, figureId);
    const readIdx = isPhoto ? readPhotoIndex : readCatalogueIndex;
    const writeIdx = isPhoto ? writePhotoIndex : writeCatalogueIndex;
    const missing = isPhoto ? 'no photo' : 'no picture';

    if (request.method === 'GET') {
      const object = await env.COLLECT.getWithMetadata(key, { type: 'arrayBuffer' });
      if (!object || !object.value) return json({ error: missing }, 404);
      return new Response(object.value, {
        headers: {
          'Content-Type': 'image/jpeg',
          'Cache-Control': 'no-store',
          'X-Photo-Hash': (object.metadata && object.metadata.hash) || '',
        },
      });
    }

    if (request.method === 'PUT') {
      const hash = (request.headers.get('X-Photo-Hash') || '').slice(0, 64);
      if (!/^[a-f0-9]{8,64}$/.test(hash)) return json({ error: 'bad hash' }, 400);
      const bytes = await request.arrayBuffer();
      if (bytes.byteLength === 0) return json({ error: 'empty' }, 400);
      if (bytes.byteLength > MAX_PHOTO_BYTES) return json({ error: 'too big' }, 413);

      const wire = `${setId}:${figureId}`;
      const index = await readIdx(env, code);
      // Already have this exact picture: costs a read, not one of the day's writes.
      if (index[wire] === hash) return json({ ok: true, unchanged: true });
      if (!(wire in index) && Object.keys(index).length >= MAX_PHOTOS) {
        return json({ error: 'too many photos' }, 507);
      }

      await env.COLLECT.put(key, bytes, { metadata: { hash, updatedAt: Date.now() } });
      index[wire] = hash;
      await writeIdx(env, code, index);
      return json({ ok: true });
    }

    if (request.method === 'DELETE') {
      const wire = `${setId}:${figureId}`;
      await env.COLLECT.delete(key);
      const index = await readIdx(env, code);
      if (wire in index) {
        delete index[wire];
        await writeIdx(env, code, index);
      }
      return json({ ok: true });
    }
    return json({ error: 'method' }, 405);
  }

  return json({ error: 'no such thing' }, 404);
}

export default {
  async fetch(request, env) {
    const cors = corsHeaders(request, env);

    if (request.method === 'OPTIONS') {
      return cors ? new Response(null, { status: 204, headers: cors })
        : new Response(null, { status: 403 });
    }
    // A browser request from somewhere else is refused outright. A request
    // with no Origin at all (curl, a script) is allowed through to the code
    // check, which is the real gate.
    if (request.headers.get('Origin') && !cors) {
      return json({ error: 'not allowed from there' }, 403);
    }

    if (await limited(request, env)) {
      return json({ error: 'slow down' }, 429, cors || {});
    }

    try {
      const response = await handle(request, env);
      if (cors) for (const [k, v] of Object.entries(cors)) response.headers.set(k, v);
      return response;
    } catch (err) {
      return json({ error: 'something broke' }, 500, cors || {});
    }
  },
};
